# -*- coding: utf-8 -*-
"""titanic_week2_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OMKTyMta9LuMX195AH0fhox8KhyGd0NU
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

OUTPUT_DIR = "week2_eda_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

DATA_URL = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

sns.set_theme(style="whitegrid")

# 1. Load dataset
df = pd.read_csv(DATA_URL)

print("=" * 70)
print("WEEK 2 - EXPLORATORY DATA ANALYSIS AND VISUALIZATION")
print("=" * 70)
print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())

# 2. Initial exploration
print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nStatistical summary:")
print(df.describe(include="all").T)

# 3. Missing values
missing = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentage": (df.isnull().mean() * 100).round(2)
}).sort_values("Missing Count", ascending=False)

print("\nMissing-value summary:")
print(missing)
missing.to_csv(os.path.join(OUTPUT_DIR, "missing_value_summary.csv"))

# 4. Prepare data for EDA
eda_df = df.copy()

eda_df["Age"] = eda_df["Age"].fillna(eda_df["Age"].median())
eda_df["Embarked"] = eda_df["Embarked"].fillna(eda_df["Embarked"].mode()[0])

eda_df["FamilySize"] = eda_df["SibSp"] + eda_df["Parch"] + 1
eda_df["IsAlone"] = (eda_df["FamilySize"] == 1).astype(int)

eda_df["AgeGroup"] = pd.cut(
    eda_df["Age"],
    bins=[0, 12, 18, 35, 60, np.inf],
    labels=["Child", "Teen", "Young Adult", "Adult", "Senior"],
    right=False
)

# 5. Survival distribution
survival = eda_df["Survived"].value_counts().sort_index()
print("\nSurvival counts:")
print(survival)

print("\nOverall survival rate:",
      round(eda_df["Survived"].mean() * 100, 2), "%")

plt.figure(figsize=(8, 5))
ax = sns.countplot(data=eda_df, x="Survived")
plt.title("Titanic Passenger Survival Distribution")
plt.xlabel("Survival Status (0 = No, 1 = Yes)")
plt.ylabel("Number of Passengers")
for container in ax.containers:
    ax.bar_label(container)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "01_survival_distribution.png"), dpi=200)
plt.show()

# 6. Gender vs survival
gender_rate = eda_df.groupby("Sex")["Survived"].mean() * 100
print("\nSurvival rate by gender:")
print(gender_rate.round(2))

plt.figure(figsize=(8, 5))
sns.countplot(data=eda_df, x="Sex", hue="Survived")
plt.title("Survival by Gender")
plt.xlabel("Gender")
plt.ylabel("Number of Passengers")
plt.legend(title="Survived", labels=["No", "Yes"])
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "02_survival_by_gender.png"), dpi=200)
plt.show()

# 7. Passenger class vs survival
class_rate = eda_df.groupby("Pclass")["Survived"].mean() * 100
print("\nSurvival rate by passenger class:")
print(class_rate.round(2))

plt.figure(figsize=(8, 5))
sns.countplot(data=eda_df, x="Pclass", hue="Survived")
plt.title("Survival by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Number of Passengers")
plt.legend(title="Survived", labels=["No", "Yes"])
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "03_survival_by_class.png"), dpi=200)
plt.show()

# 8. Age distribution
print("\nAge statistics:")
print(eda_df["Age"].describe())

plt.figure(figsize=(9, 5))
sns.histplot(data=eda_df, x="Age", bins=30, kde=True)
plt.title("Age Distribution of Titanic Passengers")
plt.xlabel("Age")
plt.ylabel("Number of Passengers")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "04_age_distribution.png"), dpi=200)
plt.show()

# 9. Age vs survival
plt.figure(figsize=(9, 5))
sns.histplot(
    data=eda_df,
    x="Age",
    hue="Survived",
    bins=30,
    kde=True,
    element="step",
    stat="density",
    common_norm=False
)
plt.title("Age Distribution by Survival Status")
plt.xlabel("Age")
plt.ylabel("Density")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "05_age_by_survival.png"), dpi=200)
plt.show()

# 10. Fare distribution
print("\nFare statistics:")
print(eda_df["Fare"].describe())

plt.figure(figsize=(9, 5))
sns.histplot(data=eda_df, x="Fare", bins=40, kde=True)
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.ylabel("Number of Passengers")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "06_fare_distribution.png"), dpi=200)
plt.show()

# 11. Fare by class
plt.figure(figsize=(9, 5))
sns.boxplot(data=eda_df, x="Pclass", y="Fare")
plt.title("Fare Distribution by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Fare")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "07_fare_by_class.png"), dpi=200)
plt.show()

# 12. Survival rate by class
plt.figure(figsize=(8, 5))
ax = sns.barplot(
    data=eda_df,
    x="Pclass",
    y="Survived",
    errorbar=None
)
plt.title("Survival Rate by Passenger Class")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "08_survival_rate_by_class.png"), dpi=200)
plt.show()

# 13. Gender and class together
pivot = pd.pivot_table(
    eda_df,
    values="Survived",
    index="Pclass",
    columns="Sex",
    aggfunc="mean"
) * 100

print("\nSurvival rate by class and gender (%):")
print(pivot.round(2))
pivot.to_csv(os.path.join(OUTPUT_DIR, "survival_by_class_gender.csv"))

plt.figure(figsize=(9, 5))
sns.barplot(
    data=eda_df,
    x="Pclass",
    y="Survived",
    hue="Sex",
    errorbar=None
)
plt.title("Survival Rate by Passenger Class and Gender")
plt.xlabel("Passenger Class")
plt.ylabel("Survival Rate")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "09_survival_class_gender.png"), dpi=200)
plt.show()

# 14. Family size
family_rate = eda_df.groupby("FamilySize")["Survived"].mean() * 100
print("\nSurvival rate by family size (%):")
print(family_rate.round(2))

plt.figure(figsize=(10, 5))
sns.barplot(data=eda_df, x="FamilySize", y="Survived", errorbar=None)
plt.title("Survival Rate by Family Size")
plt.xlabel("Family Size")
plt.ylabel("Survival Rate")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "10_survival_by_family_size.png"), dpi=200)
plt.show()

# 15. Alone vs with family
alone_rate = eda_df.groupby("IsAlone")["Survived"].mean() * 100
print("\nSurvival rate by travel status (%):")
print(alone_rate.round(2))

plt.figure(figsize=(8, 5))
sns.barplot(data=eda_df, x="IsAlone", y="Survived", errorbar=None)
plt.title("Survival Rate: Traveling Alone vs With Family")
plt.xlabel("0 = With Family, 1 = Alone")
plt.ylabel("Survival Rate")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "11_survival_alone.png"), dpi=200)
plt.show()

# 16. Age groups
age_group_rate = eda_df.groupby("AgeGroup", observed=False)["Survived"].mean() * 100
print("\nSurvival rate by age group (%):")
print(age_group_rate.round(2))

plt.figure(figsize=(10, 5))
sns.barplot(data=eda_df, x="AgeGroup", y="Survived", errorbar=None)
plt.title("Survival Rate by Age Group")
plt.xlabel("Age Group")
plt.ylabel("Survival Rate")
plt.ylim(0, 1)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "12_survival_by_age_group.png"), dpi=200)
plt.show()

# 17. Embarked vs survival
embarked_rate = eda_df.groupby("Embarked")["Survived"].mean() * 100
print("\nSurvival rate by embarkation port (%):")
print(embarked_rate.round(2))

plt.figure(figsize=(8, 5))
sns.countplot(data=eda_df, x="Embarked", hue="Survived")
plt.title("Survival by Port of Embarkation")
plt.xlabel("Port of Embarkation")
plt.ylabel("Number of Passengers")
plt.legend(title="Survived", labels=["No", "Yes"])
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "13_survival_by_embarkation.png"), dpi=200)
plt.show()

# 18. Correlation analysis
numeric_cols = [
    "Survived", "Pclass", "Age", "SibSp",
    "Parch", "Fare", "FamilySize", "IsAlone"
]

correlation = eda_df[numeric_cols].corr()

print("\nCorrelation matrix:")
print(correlation.round(2))

correlation.to_csv(
    os.path.join(OUTPUT_DIR, "correlation_matrix.csv")
)

plt.figure(figsize=(10, 7))
sns.heatmap(
    correlation,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True
)
plt.title("Correlation Matrix of Numerical Variables")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "14_correlation_heatmap.png"), dpi=200)
plt.show()

# 19. Age vs fare
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=eda_df,
    x="Age",
    y="Fare",
    hue="Survived",
    alpha=0.6
)
plt.title("Age vs Fare by Survival Status")
plt.xlabel("Age")
plt.ylabel("Fare")
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "15_age_fare_survival.png"), dpi=200)
plt.show()

# 20. Save prepared EDA dataset
eda_file = os.path.join(OUTPUT_DIR, "titanic_eda_prepared.csv")
eda_df.to_csv(eda_file, index=False)

# 21. Final summary
print("\n" + "=" * 70)
print("KEY FINDINGS")
print("=" * 70)

print(
    f"Overall survival rate: "
    f"{eda_df['Survived'].mean() * 100:.2f}%"
)

print(
    f"Female survival rate: "
    f"{gender_rate['female']:.2f}%"
)

print(
    f"Male survival rate: "
    f"{gender_rate['male']:.2f}%"
)

print(
    f"Highest class survival rate: "
    f"Class {class_rate.idxmax()} "
    f"({class_rate.max():.2f}%)"
)

print(
    f"Lowest class survival rate: "
    f"Class {class_rate.idxmin()} "
    f"({class_rate.min():.2f}%)"
)

print("\nAll EDA outputs saved in:", OUTPUT_DIR)
print("EDA completed successfully.")

import os
print(os.listdir())

from google.colab import files
files.upload()

!python titanic_week2_eda.py